name: security
on: [push, pull_request]

jobs:
  sast:
    name: SAST — Semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/python
          generateSarif: "1"
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()

  secrets:
    name: Secrets — Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint — Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning

  sca:
    name: SCA — Trivy filesystem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy fs scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 1
          format: sarif
          output: trivy_fs.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy_fs.sarif
        if: always()

  image:
    name: Image scan — Trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t flask-tp2:${{ github.sha }} .
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: flask-tp2:${{ github.sha }}
          severity: CRITICAL
          exit-code: 1
          format: sarif
          output: trivy_image.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy_image.sarif
        if: always()
